/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lz_example_android_jni_sample_JniUtils */

#ifndef _Included_com_lz_example_android_jni_sample_JniUtils
#define _Included_com_lz_example_android_jni_sample_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lz_example_android_jni_sample_JniUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lz_example_android_1jni_1sample_JniUtils_getStringFormC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
